# Generated by Django 3.2.5 on 2021-07-22 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d638b06f-fd44-4695-9871-052e28eebd9d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
