# Generated by Django 3.2.5 on 2021-07-22 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210722_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c66dae0a-2089-4de4-9fa0-12cf39ba7c79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b123b64a-9e0b-4f45-8bff-f2af98089115'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83a1294a-771f-48d5-abba-67259f77642e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
