# Generated by Django 3.2.5 on 2021-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210722_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='pattern.jpg', null=True, upload_to=''),
        ),
    ]
